env:
  global:
    CC_TEST_REPORTER_ID=6b34fd5887d0fd8e9d237dc0b480cb650907078314e9034b79057e032bf11450
language: ruby
rvm:
- 2.5.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle install
  - bundle exec rubocop
  - bundle exec rspec spec
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
